# Generated by Django 5.0.1 on 2024-01-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_werewolfsaga_werewolfsagaplayer_werewolfsaga_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
