# Generated by Django 5.0.1 on 2024-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='werewolfsaga',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='werewolfsaga',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
