# Generated by Django 5.0.1 on 2024-01-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_rename_subscribers_chatroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='werewolfsagaplayer',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
